# Data
{{cookiecutter.repo_name}}data:
  image: busybox
  volumes:
    - /var/lib/postgresql/data
    - /data

# PostgreSQL
postgres:
  image: postgres:9.4
  volumes_from:
    - {{cookiecutter.repo_name}}data
  environment:
    - POSTGRES_PASSWORD={{cookiecutter.postgres_password}}

# Redis
redis:
  image: redis
  volumes_from:
    - {{cookiecutter.repo_name}}data

# Nginx
nginx:
  image: nginx
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./web/media:/media:ro
    - ./web/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/static:/static:ro
  links:
    - web

# pgweb
pgweb:
  image: donnex/pgweb
  links:
    - postgres
  environment:
    VIRTUAL_HOST: pgweb.{{cookiecutter.virtual_host}}

# Assets
assets:
  image: donnex/assets
  ports:
    - "35729:35729"
  volumes:
    - ./assets/gulpfile.js:/gulp/gulpfile.js
    - ./web/{{cookiecutter.repo_name}}/sass:/gulp/sass
    - ./web/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/static/css:/gulp/css
    - ./web/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/static/js:/gulp/js

# Web python
web:
  build: ./web
  volumes:
    - ./web/media:/media
    - ./web/{{cookiecutter.repo_name}}:/wwwroot:ro
  links:
    - postgres
    - redis
  environment:
    - DJANGO_CONFIGURATION=Dev
    - DJANGO_SECRET_KEY={{cookiecutter.django_secret_key}}
    - DJANGO_HIREDIS_CACHE_LOCATION=redis:6379
    - DJANGO_ALLOWED_HOSTS=""
    - DATABASE_URL=postgres://postgres:{{cookiecutter.postgres_password}}@postgres/{{cookiecutter.repo_name}}?sslmode=disable
    - EMAIL_URL=console://
    - VIRTUAL_HOST={{cookiecutter.virtual_host}}
  command: gunicorn --log-level info --log-file=- --workers 4 --name {{cookiecutter.repo_name}}_gunicorn -b 0.0.0.0:8000 --reload {{cookiecutter.repo_name}}.wsgi:application
